### ISSUE TITLE
About Output resolution

### ISSUE THREAD

**Issue by harisreedhar** [Seungeun-Han/SCANet_Real-Time_Face_Parsing_Using_Spatial_and_Channel_Attention#1]
Is onnx model output resolution only ``64 x 64``?

**Comment by Seungeun-Han** [comment]
That's right. When the input size is 256x256, the model output resolution is 64x64. So, you need to resize it to match the input size.

**Comment by harisreedhar** [comment]
Does the model support higher resolution? Upscaling with Bilinear Interpolation produces blurry result.

**Comment by Seungeun-Han** [comment]
The current model does not support higher resolution. While increasing the size of the input data will proportionally increase the size of the model output, the resolution will still be reduced compared to the original size.
